regions:
  - ap-northeast-1
  - us-east-1
  - global
account-blocklist:
  - "999999999999"
resource-types:
  excludes:
    - IAMRole
    - IAMRolePolicyAttachment
    - IAMSAMLProvider
    - IAMRolePolicy
    - ACMCertificate
accounts:
  "999999999999": {}